const el=(id)=>document.getElementById(id)

const state={
  header:{style:{position:"sticky",top:0},isLoadingSession:true,errorSession:null,isLoggedIn:false,entries:[{id:"home",label:"首页",route:"P001",isVisible:true},{id:"search",label:"查询",route:"P002",isVisible:true},{id:"profile",label:"个人中心",route:"P006",isVisible:true}],entryLogin:{id:"login",label:"登录",route:"P003",isVisible:true},entryRegister:{id:"register",label:"注册",route:"P004",isVisible:true},activeRoute:"P001",redirecting:false,navigationTarget:null,userDisplay:{username:null,avatarUrl:null},userMenu:{isOpen:false,items:["个人中心","退出登录"]}},
  quick:{baseEntries:[{id:"ticket-search",label:"车票查询",route:"P002"},{id:"order-search",label:"订单查询",route:"P006"},{id:"change-refund",label:"改签退票",route:"P006",operation:"change_or_refund"}],isLoggedIn:false,isLoadingRecommendations:false,errorRecommendations:null,recommendations:[],isLoadingHistory:false,errorHistory:null,historyItems:[],hasDegraded:false,fallbackEnabled:false,confirmDialog:{isVisible:false},redirecting:false,navigationTarget:null,populatedSearchForm:null}
}

function setActiveRoute(route){state.header.activeRoute=route;state.header.entries=state.header.entries.map(e=>({...e,isHighlighted:e.route===route}))}
function clickLogin(){state.header.redirecting=true;state.header.navigationTarget="P003"}
function clickRegister(){state.header.redirecting=true;state.header.navigationTarget="P004"}

async function getSession(){const res=await fetch('/api/session',{headers:{Authorization:'Bearer valid'}});if(res.status===200)return res.json();const err=await res.json();const e=new Error(err.message);e.status=res.status;throw e}
async function getRecommendations(userId,forceError){const url=forceError?`/api/recommendations?userId=${userId}&error=1`:`/api/recommendations?userId=${userId}`;const res=await fetch(url,{headers:{Authorization:'Bearer valid'}});if(res.status===200){const body=await res.json();return body.items}const err=await res.json();const e=new Error(err.message);e.status=res.status;throw e}
async function getSearchHistory(userId,limit){const res=await fetch(`/api/search-history?userId=${userId}&limit=${limit}`,{headers:{Authorization:'Bearer valid'}});if(res.status===200){const body=await res.json();return body.items}const err=await res.json();const e=new Error(err.message);e.status=res.status;throw e}
async function deleteSearchHistory(userId){const res=await fetch(`/api/search-history?userId=${userId}&scope=all`,{method:'DELETE',headers:{Authorization:'Bearer valid'}});if(res.status===200){const body=await res.json();return body.deletedCount}const err=await res.json();const e=new Error(err.message);e.status=res.status;throw e}

function renderHeader(){const root=el('header-root');root.innerHTML='';const nav=document.createElement('div');nav.className='header-bar';const left=document.createElement('div');left.className='logo';left.textContent='中国铁路12306';const right=document.createElement('div');right.className='nav-items';state.header.entries.forEach(e=>{const a=document.createElement('a');a.textContent=e.label;a.href='#';if(e.isHighlighted)a.classList.add('active');right.appendChild(a)});if(!state.header.isLoggedIn){const login=document.createElement('button');login.textContent='登录';login.onclick=()=>{clickLogin();renderHeader();};const reg=document.createElement('button');reg.textContent='注册';reg.onclick=()=>{clickRegister();renderHeader();};right.appendChild(login);right.appendChild(reg)}else{const user=document.createElement('div');user.className='user-display';user.textContent=state.header.userDisplay.username||'用户';right.appendChild(user)}nav.appendChild(left);nav.appendChild(right);root.appendChild(nav)}

function renderQuick(){const root=el('quick-root');root.innerHTML='';const grid=document.createElement('div');grid.className='quick-grid';state.quick.baseEntries.forEach(b=>{const card=document.createElement('div');card.className='quick-card';card.textContent=b.label;card.onclick=()=>{state.quick.redirecting=true;state.quick.navigationTarget=b.route};grid.appendChild(card)});root.appendChild(grid);if(state.quick.isLoggedIn&&state.quick.recommendations.length>0){const rec=document.createElement('div');rec.className='rec-section';const title=document.createElement('h3');title.textContent='个性化推荐';rec.appendChild(title);state.quick.recommendations.forEach(r=>{const item=document.createElement('div');item.className='rec-item';item.textContent=r.label;rec.appendChild(item)});root.appendChild(rec)}const hist=document.createElement('div');hist.className='hist-section';const htitle=document.createElement('h3');htitle.textContent='历史查询';hist.appendChild(htitle);const list=document.createElement('ul');state.quick.historyItems.forEach(h=>{const li=document.createElement('li');li.textContent=`${h.fromStation}  ${h.toStation} ${h.travelDate}`;li.onclick=()=>{state.quick.populatedSearchForm={from:h.fromStation,to:h.toStation,date:h.travelDate};el('fromStation').value=h.fromStation;el('toStation').value=h.toStation;el('travelDate').value=h.travelDate};list.appendChild(li)});hist.appendChild(list);const clearBtn=document.createElement('button');clearBtn.textContent='清除历史记录';clearBtn.onclick=async()=>{state.quick.confirmDialog.isVisible=true;state.quick.historyItems=[];renderQuick();state.quick.confirmDialog.isVisible=false;const deleted=await deleteSearchHistory('u1');if(deleted>0){state.quick.historyItems=[];renderQuick()}};hist.appendChild(clearBtn);root.appendChild(hist)}

function init(){setActiveRoute('P001');renderHeader();state.header.isLoadingSession=true;getSession().then(data=>{state.header.isLoadingSession=false;state.header.isLoggedIn=true;state.header.userDisplay.username=data.username;state.header.userDisplay.avatarUrl=data.avatarUrl;renderHeader();state.quick.isLoggedIn=true;return Promise.all([getRecommendations('u1'),getSearchHistory('u1',5)])}).then(([recs,hist])=>{state.quick.recommendations=recs;state.quick.historyItems=[...hist].sort((a,b)=>a.createdAt<b.createdAt?1:-1).slice(0,5);renderQuick()}).catch(e=>{state.header.isLoadingSession=false;if(e.status===401){state.header.redirecting=true;state.header.navigationTarget='P003'}renderHeader();renderQuick()});const searchBtn=el('searchBtn');searchBtn.onclick=()=>{};const breadcrumb=el('breadcrumb');breadcrumb.textContent='北京→上海';}

document.addEventListener('DOMContentLoaded',init)