const { createServer } = require('http')
const { readFileSync, existsSync, createReadStream } = require('fs')
const { extname, join, normalize } = require('path')

function contentType(path){const ext=extname(path).toLowerCase();switch(ext){case '.html':return 'text/html; charset=utf-8';case '.css':return 'text/css; charset=utf-8';case '.js':return 'application/javascript; charset=utf-8';case '.png':return 'image/png';case '.jpg':case '.jpeg':return 'image/jpeg';case '.svg':return 'image/svg+xml';case '.ico':return 'image/x-icon';default:return 'application/octet-stream'}}

function serveStatic(filePath,res){if(!existsSync(filePath)){res.statusCode=404;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({code:'NOT_FOUND',message:'Static file not found'}));return}res.statusCode=200;res.setHeader('Content-Type',contentType(filePath));createReadStream(filePath).pipe(res)}

const UI_DIR=normalize(join(__dirname,'ui'))

function apiApp(req,res){const url=new URL(req.url||'', 'http://localhost');const send=(status,body)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(body))};const auth=req.headers['authorization'];if(req.method==='GET'&&url.pathname==='/api/session'){if(auth==='Bearer valid')return send(200,{userId:'u1',username:'张三',avatarUrl:'/avatar.png'});return send(401,{code:'UNAUTHORIZED',message:'Token 缺失或过期'})}if(req.method==='GET'&&url.pathname==='/api/recommendations'){if(auth!=='Bearer valid')return send(401,{code:'UNAUTHORIZED',message:'未登录用户调用'});if(url.searchParams.get('error')==='1')return send(500,{code:'INTERNAL_ERROR',message:'推荐服务异常'});return send(200,{items:[{id:'r1',label:'推荐1',route:'P002',score:0.9},{id:'r2',label:'订单管理',route:'P006',score:0.7}]})}if(url.pathname==='/api/search-history'){if(auth!=='Bearer valid')return send(401,{code:'UNAUTHORIZED',message:'未登录用户调用'});if(req.method==='GET'){const all=[{id:'1',fromStation:'北京',toStation:'上海',travelDate:'2025-11-25',createdAt:'2025-11-22T12:00:00Z'},{id:'2',fromStation:'北京',toStation:'杭州',travelDate:'2025-11-24',createdAt:'2025-11-22T13:00:00Z'},{id:'3',fromStation:'北京',toStation:'南京',travelDate:'2025-11-23',createdAt:'2025-11-22T14:00:00Z'},{id:'4',fromStation:'北京',toStation:'天津',travelDate:'2025-11-22',createdAt:'2025-11-22T15:00:00Z'},{id:'5',fromStation:'北京',toStation:'苏州',travelDate:'2025-11-21',createdAt:'2025-11-22T16:00:00Z'},{id:'6',fromStation:'北京',toStation:'无锡',travelDate:'2025-11-20',createdAt:'2025-11-22T17:00:00Z'}];const sorted=all.sort((a,b)=>a.createdAt<b.createdAt?1:-1).slice(0,5);return send(200,{items:sorted})}if(req.method==='DELETE'){return send(200,{deletedCount:6})}}
return send(404,{code:'NOT_FOUND',message:'Unknown route'})}

const server=createServer((req,res)=>{const url=new URL(req.url||'/', 'http://localhost');if(url.pathname.startsWith('/api'))return apiApp(req,res);if(url.pathname==='/'||url.pathname==='/index.html'){const primary=join(UI_DIR,'index.html');const fallback=join(UI_DIR,'P001.html');return serveStatic(existsSync(primary)?primary:fallback,res)}if(url.pathname.startsWith('/ui/')){const rel=url.pathname.replace('/ui/','');return serveStatic(join(UI_DIR,rel),res)}const uiTry=join(UI_DIR,url.pathname.replace(/^\//,''));if(existsSync(uiTry))return serveStatic(uiTry,res);res.statusCode=404;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({code:'NOT_FOUND',message:'Unknown route'}))})

const PORT=process.env.PORT?Number(process.env.PORT):5173
server.listen(PORT,()=>{console.log(`Dev server running at http://localhost:${PORT}/`)})